### ISSUE TITLE
Verification state appears to persist across sessions

### ISSUE THREAD

**Issue by philbooth** [mozilla/PyFxA#47] opened 2016-12-29 14:24 UTC
The following script, when run with appropriate `SYNC_EMAIL` and `SYNC_PASSWORD` environment variables, is expected to fail with `fxa.errors.ClientError: Unverified account`.

```python
import os
from fxa.core import Client

client = Client("https://api.accounts.firefox.com")

session = client.login(os.environ['SYNC_EMAIL'], os.environ['SYNC_PASSWORD'], keys=True)

email_status = session.get_email_status()
print email_status

session.fetch_keys()
```

And for me, it does indeed fail every time. However it's been reported that, after completing sign-in confirmation once, the script stops failing on subsequent invocations. All subsequent attempts to fetch keys succeed and `email_status` indicates that `sessionVerified` is true.

To be clear, concrete steps to reproduce are:

1. Set `SYNC_EMAIL` and `SYNC_PASSWORD` environment variables for your account.
2. Run the script, expect it to fail, see it fail.
3. Check your email, then follow the sign-in confirmation link after it arrives.
4. Run the script again, expect it to fail, see it succeed instead.

This was reported in IRC by @ecksun, who also mentioned that they don't see equivalent behaviour when doing the same thing using `fxa-js-client`. Is there something peculiar to PyFxA going on here?

**Comment by rfk** [comment] 2017-01-02 19:11
This sounds like it might be due to the new "ip history" feature where we allowlist your IP for 24 hours after a successful login:

  https://github.com/mozilla/fxa-auth-server/blob/master/lib/routes/account.js#L678

**Comment by ecksun** [comment] 2017-01-02 19:33
Should I not then see the same behavior across clients? I can only see this behavior with the python client.

If you have any particular tests you would like me to run I'm happy to oblige.

**Comment by rfk** [comment] 2017-01-02 20:02
> Should I not then see the same behavior across clients?

Indeed you should; @ecksun what other clients did you try, and where they connecting from the same IP address each time?

**Comment by ecksun** [comment] 2017-01-02 21:01
> Indeed you should; @ecksun what other clients did you try, and where they connecting from the same IP address each time?

I tried `fxa-js-client`, and it was from the same machine. I was very confused because I couldn't get my node code working, which seemed to be working fine with python, I thus continually tried them both to try to debug the issue.

If its interesting, I can post that code as well, but it is semantically equivalent to the python code above.

**Comment by rfk** [comment] 2017-01-02 21:18
> If its interesting, I can post that code as well,

Please do, I'd be interested to get to the bottom of this.

**Comment by ecksun** [comment] 2017-01-03 18:33
Sure, I just ran the test again with this javascript:

```node
'use strict';

const FxAccountsClient = require('fxa-js-client');

const client = new FxAccountsClient('https://api.accounts.firefox.com/v1');

function printResponse(prefix) {
    return (resp) => {
        console.log(`Response for ${prefix}:`);
        console.dir(resp);
        return resp;
    };
}

client.signIn(process.env.SYNC_EMAIL, process.env.SYNC_PASSWORD, {
    keys: true
}) .then(creds => {
    return client.recoveryEmailStatus(creds.sessionToken);
}).then(resp => {
    console.log(resp);
});
```

This is the result:

```
$ make test-js 
npm start

> fxa@1.0.0 start /home/xun/tmp/fxa
> node client.js

{ email: 'ecksun@gmail.com',
  verified: false,
  sessionVerified: false,
  emailVerified: true }


# Confirm email

$ make test-js 
npm start

> fxa@1.0.0 start /home/xun/tmp/fxa
> node client.js

{ email: 'ecksun@gmail.com',
  verified: false,
  sessionVerified: false,
  emailVerified: true }
```

I then ran the python client:

```
$ make test-py 
venv/bin/python client.py
... 
status:  {u'emailVerified': True, u'verified': True, u'email': u'ecksun@gmail.com', u'sessionVerified': True}
```

I ran all of this from [this repository](https://gitlab.com/ecksun/fxa-test), to make it easier to reproduce.

**Comment by rfk** [comment] 2017-01-05 03:43
I can confirm reproducibility of this behaviour on my machine, but I don't yet understand what's going on...

**Comment by rfk** [comment] 2017-01-05 03:58
Aha, I figured it out!  This is not a bug, although it's certainly unexpected behaviour from the user perspective, and unfortunately I can't share all the details of why it's happening because they're related to security measures.

Basically though, we do have logic that says "if you logged in from this IP within the last 24 hours, you can skip sign-in confirmation":

  * https://github.com/mozilla/fxa-auth-server/blob/69552618cf98f996d10ba399f71211059a16fbf9/lib/routes/account.js#L694

But we also have logic that says "if the request looks unusual, you're not allowed to skip sign-in confirmation":

  * https://github.com/mozilla/fxa-auth-server/blob/69552618cf98f996d10ba399f71211059a16fbf9/lib/routes/account.js#L676
  
The requests being sent by the node-js client are "more suspicious" than the ones being sent by the python client.  I can't go into why because we keep the details of what constitutes a "suspicious" request confidential, for hopefully obvious reasons.  But we could consider tweaking that filter to be more consistent here.

I'm going to close this out as it's not a bug in PyFxA, but thanks for reaching out to work through what's going on here, and I'm glad we got to the bottom of it even if I can't share all the precise details.

(And if you *do* happen to hack around with the node-js client and figure out how to make it send less "suspicious-looking" requests, please don't post the details here :-)

**Closed by rfk** 2017-01-05 03:58 UTC

**Comment by rfk** [comment] 2017-01-05 04:00
For other core devs with access to the private repo, to security measure that's tripping  and causing the difference in behaviour here is:

  https://github.com/mozilla/fxa-customs-server-private/blob/train-72/lib/server.js#L169

**Comment by ecksun** [comment] 2017-01-07 11:33
That is very interesting, thanks for the summary :)
